# CLAIM EXTRACTION CONFIG
CLAIM_EXTRACTOR_MODEL_PATH = "yevhenkost/claim-detection-claimbuster-binary-TinyBERT_General_4L_312D"
CLAIM_EXTRACTOR_KEEP_LOGIT_IDX = 1
CLAIM_EXTRACTOR_CONFIDENCE_THOLD = 0.75
CLAIM_EXTRACTOR_BATCH_SIZE = 8

# ALIGNMENT CONFIG VARIABLES
ALIGNER_MODEL_PATH = "yevhenkost/cutiesRun28-05-2020-roberta-base-evidenceAlignment"
ALIGNER_BATCH_SIZE = 6

# SCORING CONFIG VARIABLES
SCORING_MODEL = "roberta-large-mnli"
SCORING_MODEL_LABEL_DECODER = {"entailment": 2, "contradiction": 0}
SCORER_BATCH_SIZE = 6

# CLAIM WORTHINESS VARIABLES
CLAIM_WORTHINESS_MODEL = "yevhenkost/claimbuster-yesno-binary-bert-base-cased"
CLAIM_WORTHINESS_BATCH_SIZE = 6
CLAIM_WORTHINESS_ID2LABEL = {0: "NO", 1: "YES"}
CLAIM_WORTHINESS_CONFIDENCE_THOLD = 0.8